apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  selector:
    matchLabels:
      run: vscode
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: vscode
    spec:
      containers:
      - name: vscode
        image: ghcr.io/wisteriafloribunda/vscode-tunnel
        securityContext:
            privileged: true
        volumeMounts:
          - mountPath: /home/workspace
            name: data
          - mountPath: /root
            name: pldata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vscode-data-pvc
        - name: pldata
          persistentVolumeClaim:
            claimName: vscode-pl-pvc
