apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  selector:
    matchLabels:
      editor: vscode
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: vscode
        image: ghcr.io/wisteriafloribunda/vscode-tunnel
        workingDir: /home/workspace
        securityContext:
            privileged: true
        volumeMounts:
         - mountPath: /home/workspace
           name: vscode-data-pvc
        resources:
          limits:
            cpu: 3
            memory: 6Gi
      volumes:
        - name: vscode-data-pvc
          persistentVolumeClaim:
            claimName: vscode-data-pvc
