apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  selector:
    matchLabels:
      run: vscode
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: vscode
    spec:
      containers:
      - name: vscode
        image: ghcr.io/wisteriafloribunda/vscode-tunnel
        securityContext:
            privileged: true
        volumeMounts:
         - mountPath: /home/workspace
           name: workspace
         - mountPath: /root
           name: rot
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: vscode-data-pvc
        - name: rot
          persistentVolumeClaim:
            claimName: vscode-pl-pv