apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  selector:
    matchLabels:
      run: vscode
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: vscode
    spec:
      containers:
      - name: vscode
        image: ghcr.io/wisteriafloribunda/vscode-tunnel
        securityContext:
            privileged: true
