apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  selector:
    matchLabels:
      editor: vscode
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: vscode
        image: ghcr.io/wisteriafloribunda/vscode-tunnel
        workingDir: /home/workspace
        securityContext:
            privileged: true
        volumeMounts:
          - mountPath: /home/workspace
            name: data
          - mountPath: /root
            name: pl
        resources:
          limits:
            cpu: 3
            memory: 6Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vscode-data-pvc
        - name: pl
          persistentVolumeClaim:
            claimName: vscode-pl-pvc
