apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-pl-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8s/vscode-data/root"
