kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vscode-pl-pvc
  annotations:
    volume.beta.kubernetes.io/persistent-volume: vscode-pl-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
