apiVersion: v1
kind: Service
metadata:
  name: vscode-service
  labels:
    run: vscode
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: vscode
