apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      run: mysql
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        securityContext:
            privileged: true
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
         - mountPath: /var/lib/mysql
           name: data
         - mountPath: /etc/mysql/conf.d
           name: config
         - mountPath: /docker-entrypoint-initdb.d
           name: initdb
        ports:
            - containerPort: 3306
        resources:
          limits:
            cpu: 3
            memory: 3Gi
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: "127.0.0.1"
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_USER
          value: "root"
        - name: PMA_PASSWORD
          value: "root"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: mysql-config-pvc
        - name: initdb
          persistentVolumeClaim:
            claimName: mysql-initdb-pvc
