apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      editor: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        editor: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        securityContext:
            privileged: true
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
         - mountPath: /var/lib/mysql
           name: data
         - mountPath: /etc/mysql/conf.d
           name: config
         - mountPath: /docker-entrypoint-initdb.d
           name: initdb
        ports:
            - containerPort: 3306
              name: mysql  
        resources:
          limits:
            cpu: 3
            memory: 3Gi
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        ports:
        - containerPort: 80
          name: phpmyadmin
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: mysql-config-pvc
        - name: initdb
          persistentVolumeClaim:
            claimName: mysql-initdb-pvc
