apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-initdb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k8s/mysql-data/initdb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-initdb-pvc
  annotations:
    volume.beta.kubernetes.io/persistent-volume: mysql-initdb-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
