apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    run: mysql
spec:
  type: LoadBalancer
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: phpmyadmin
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: mysql
  loadBalancerIP: 192.168.1.100