apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  type: LoadBalancer
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: phpmyadmin
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: mysql
  loadBalancerIP: 192.168.1.100